version: 2

sources:
  - name: sap_adw
    description: Réplica do banco Postgres da adventure works contendo dados do SAP
    schema: sap_adw
    tables:
      - name: product
        description: Uma linha por produto. Inclui pedidor descontinuados.
        columns:
          - name: productid
            description: Chave primária da tabela de produtos.
            tests:
              - unique
              - not_null

      - name: salesorderheader
        description: Uma linha por pedido (venda).
        columns:
          - name: salesorderid
            description: Chave primária da tabela de vendas.
            tests:
              - unique
              - not_null

          - name: status
            description: Número inteiro representando o status do pedido
            tests:
              - not_null

          - name: customerid
            description: Chave estrangeira para o id do cliente.
            tests:
              - relationships:
                  to: ref('customer')
                  field: customerid

          - name: salespersonid
            description: Chave estrangeira para o id do vendedor.
            tests:
              - relationships:
                  to: ref('salesperson')
                  field: businessentityid

          - name: territoryid
            description: Chave estrangeira para o id da região destinatária do pedido.
            tests:
              - relationships:
                  to: ref('salesterritory')
                  field: territoryid

          - name: creditcardid
            description: Chave estrangeira para o id do cartão de crédito.
            tests:
              - relationships:
                  to: ref('creditcard')
                  field: creditcardid

      - name: salesorderdetail
        description: Cada linha detalha informações de produtos contidos nos pedidos.
        columns:
          - name: salesorderdetailid
            description: Chave primária da tabela.
            tests:
              - unique
              - not_null

          - name: salesorderid
            description: Chave estrangeira para o id do pedido.
            tests:
              - relationships:
                  to: ref('salesorderheader')
                  field: salesorderid

          - name: productid
            description: Chave estrangeira para o id do produto.
            tests:
              - relationships:
                  to: ref('product')
                  field: productid

      - name: salesorderheadersalesreason
        description: Uma linha por pedido. Esta tabela relaciona um pedido com um motivador da venda (salesreason).
        columns:
          - name: salesorderid
            description: Chave estrangeira para o id do pedido.
            tests:
              - relationships:
                  to: ref('salesorderheader')
                  field: salesorderid

          - name: salesreasonid
            description: Chave estrangeira para o id do motivo da venda.
            tests:
              - relationships:
                  to: ref('salesreason')
                  field: salesreasonid

      - name: salesreason
        description: Categorias que descrevem o motivador da venda.
        columns:
          - name: salesreasonid
            description: Chave primária da tabela
            tests:
              - unique
              - not_null

          - name: name
            description: Motivador da venda
            tests:
              - accepted_values:
                  values:
                    [
                      "Price",
                      "Manufacturer",
                      "Review",
                      "Quality",
                      "Other",
                      "Magazine Advertisement",
                      "Television  Advertisement",
                      "Demo Event",
                      "Sponsorship",
                      "On Promotion",
                    ]

          - name: reasontype
            description: Tipo de motivador.
            tests:
              - accepted_values:
                  values: ["Other", "Marketing", "Promotion"]

      - name: customer
        description: Uma linha por cliente.
        columns:
          - name: customerid
            description: Chave primária da tabela de clientes.
            tests:
              - unique
              - not_null

          - name: personid
            description: Chave estrangeira para o id da pessoa.
            tests:
              - relationships:
                  to: ref('person')
                  field: businessentityid

      - name: creditcard
        description: Uma linha por cartão de crédito.

      - name: address
        description: Uma linha por endereço.
        columns:
          - name: addressid
            description: Chave primária da tabela de endereços..
            tests:
              - unique
              - not_null

          - name: stateprovinceid
            description: Chave estrangeira para o id do estado (stateprovince).
            tests:
              - relationships:
                  to: ref('stateprovince')
                  field: stateprovinceid

          - name: addressline1
            description: Primeira parte do endereço

          - name: addressline2
            description: Segunda parte do endereço

          - name: city
            description: Nome da cidade.

      - name: stateprovince
        description: Uma linha por estado.
        columns:
          - name: stateprovinceid
            description: Chave primária da tabela de estados.
            tests:
              - unique
              - not_null

          - name: name
            description: Nome do estado.

          - name: territoryid
            description: Chave estrangeira para o id do país (salesterritory)
            tests:
              - relationships:
                  to: ref('salesterritory')
                  field: territoryid

      - name: person
        description: Uma linha por pessoa.

      - name: store
        description: Uma linha por estabelecimento.
