from .PedidosAgregadosGraph import PedidosAgregadosGraph
from .QuantidadeCompradaAgregadosGraph import QuantidadeCompradaAgregadosGraph
from .TotalNegociadoAgregadosGraph import TotalNegociadoAgregadosGraph
from .MapaMundiMetricasGraph import MapaMundiMetricasGraph
from .PedidosTemporalGraph import PedidosTemporalGraph
from .TicketMedioAgregadosGraph import TicketMedioAgregadosGraph
from .MetricasTotaisFiltrados import MetricasTotaisFiltrados
from .MelhoresClientesGraph import MelhoresClientesGraph